// examples/vue/vue-basic/src/pages/Route.vue
<template>
  <main>
    <nav>
      <button 
        @click="nav.navigate('/home')">
        Home
      </button>
      <button 
        @click="nav.navigate('/about')">
        About
      </button>
      <button 
        class="anchored"
        @click="nav.navigate('/more')">
        More &gt;
      </button>
    </nav>
    <h1>{{ req.pathname }}</h1>
  </main>
</template>

<script>
export default {
  props: {
    nav: null,
    req: null
  }
}
</script>

// examples/react/create-react-app/src/pages/route.jsx
import React from 'react'
import { useAppContext } from '../context'

export const Route = () => {
    const { router } = useAppContext()
    return <div>
        <nav>
            <button 
                onClick={() => router.navigate('/home')}>
                Home
            </button>
            <button
                onClick={() => router.navigate('/about')}>
                About
            </button>
            <button
                className="anchored" 
                onClick={() => router.navigate('/more')}>
                More &gt;
            </button>
        </nav>
        <h1>{ router.currentReq.routePattern }</h1>
        {/* <pre>{ JSON.stringify(req, null, 4) }</pre> */}
    </div>
}
