// examples/react/create-react-app/src/pages/more.jsx
import React, {useState} from 'react'
import { useAppContext } from '../context'

export const More = () => {
    // const { router } = useAppContext()
    const [v]= useState('test')

    return <div>
        {v}
        {/* <nav>
            <button 
                onClick={() => router.back()}>
                &lt; Back
            </button>
        </nav>
        <h1>{ router.currentReq.routePattern }</h1> */}
    </div>
}

// examples/vue-animated/src/pages/More.vue
<template>
    <main>
        <nav>
            <button 
              @click="nav.back()">
              &lt; Back
            </button>
        </nav>
        <h1>{{ req.routePattern }}</h1>
    </main>
</template>

<script>
export default {
  props: {
    nav: null,
    req: null
  }
}
</script>
